fix(sdk): `Room::event_with_context` stops inserting events in the Event Cache.
This patch removes the insertion of events retrieved from `/context`
with `Room::event_with_context` in the Event Cache. This was implemented
as a “workaround” but it creates a compilation problem now:

```
error[E0391]: cycle detected when computing
type of `paginators::room::<impl at
crates/matrix-sdk/src/paginators/room.rs:385:1:
385:28>::event_with_context::{anon_assoc#0}`
```

`event_cache::EventCache`, via `event_cache::caches::Caches`, owns
an `event_cache::caches::event_focused::EventFocusedCache`, where
`EventFocusedCache::reload_impl` calls `Paginator::start_from`, which
calls `Room::event_with_context`, which calls `event_cache::EventCache`.
We have our cycle in a query (I'm not sure which query, but I suspect a
query to know if a type inside the Event Cache is `std::marker::Send`).

Either, the Paginator is used outside an Event Cache context and we
don't really care to insert events in it, especially because it doesn't
save a future call to `/context`. Either, the Paginator is used inside
an Event Cache context and events returned by the Paginator are very
likely to be stored at some point. So technically, this code does not
make sense.

It is confirmed by the fact that `Room::event_with_context`
is only called by `NotificationClient` (which doesn't care
about the Event Cache at the time of writing), and by `<Room
as PaginableRoom>::event_with_context`, which is **only**
called by `Paginator::start_from` which is only called by…
`EventFocusedCache::reload_impl`! So the only relevant consumer here is
the Event Cache.
Inside `EventFocusedCache`, events are not stored in the database, they
are only kept in-memory, but that's by design. If we wanted to keep
these events in the database, it would be the place to do so — not in
the `Room::event_with_context`.